### ISSUE TITLE
No telephone

### ISSUE THREAD

**Issue by 1Jesper1** [TriDiscord/twrp_device_samsung_goya#1]
https://github.com/TriDiscord/twrp_device_samsung_goya/blob/1bbad0c652081c09c8c90d1616145f93416e89fc/omni_goya.mk#L4

**Comment by TriDiscord** [comment]
Thanks for the issue! Will be fixed right away.

**Comment by TriDiscord** [comment]
Actually, this is needed for goya3g device, and it won't really affect the behavior of goyawifi, only there for compatibility purposes for the 3G variant.
