### ISSUE TITLE
Mount points

### ISSUE THREAD

**Issue by 1Jesper1** [TriDiscord/twrp_device_samsung_goya#3]
https://github.com/gr8nole/android_device_samsung_goyawifi/blob/master/recovery/twrp.fstab

https://github.com/TriDiscord/twrp_device_samsung_goya/blob/android-4.4/recovery.fstab

Are all mount points the same?

**Comment by TriDiscord** [comment]
Hi! TWRP's `init.rc` uses `/boot` instead of `/kernel`. Patches have been made accordingly to the `init.rc` file.

The `/preload` partition will be added soon, thanks for bringing that to my attention.

**Comment by TriDiscord** [comment]
Fixed in https://github.com/TriDiscord/twrp_device_samsung_goya/commit/dd953a4fdbef41140166fcd05ec998f7ceac592c
