### ISSUE TITLE
AndroidBoardVendor.mk needed?

### ISSUE THREAD

**Issue by 1Jesper1** [TriDiscord/twrp_device_samsung_goya#4]
https://github.com/TriDiscord/twrp_device_samsung_goya/blob/19c1d631b388939449eb99a1860c8e282bed0485/AndroidBoard.mk#L8

https://github.com/gr8nole/android_device_samsung_goyawifi/blob/master/AndroidBoard.mk

**Comment by TriDiscord** [comment]
gr8nole copied that placeholder from lt02wifi

**Comment by TriDiscord** [comment]
gr8nole copied that placeholder from lt02wifi
