### ISSUE TITLE
TARGET_RECOVERY_PIXEL_FORMAT differs

### ISSUE THREAD

**Issue by 1Jesper1** [TriDiscord/twrp_device_samsung_goya#5]
https://github.com/TriDiscord/twrp_device_samsung_goya/blob/19c1d631b388939449eb99a1860c8e282bed0485/BoardConfig.mk#L53

TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565" 
https://github.com/gr8nole/android_device_samsung_goyawifi/blob/6771f836bbda5101b3d1da57acf3b98e5b6e4235/BoardConfig.mk#L49

**Comment by TriDiscord** [comment]
https://github.com/T110-android/android_device_samsung_goya-common/blob/0008e9e09126fa25bb8b71dc5a8b7b5718784174/BoardConfigCommon.mk#L175

Might be changed to RGBX_8888, but currently not the issue
