### ISSUE TITLE
BoardConfigVendor needed?

### ISSUE THREAD

**Issue by 1Jesper1** [TriDiscord/twrp_device_samsung_goya#6]
-include vendor/samsung/goyawifi/BoardConfigVendor.mk

https://github.com/gr8nole/android_device_samsung_goyawifi/blob/6771f836bbda5101b3d1da57acf3b98e5b6e4235/BoardConfig.mk#L17

**Comment by TriDiscord** [comment]
gr8nole copied that placeholder from lt02wifi
